# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Sun May 14 16:04:25 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 700)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.mainGView = QtGui.QGraphicsView(self.centralWidget)
        self.mainGView.setGeometry(QtCore.QRect(20, 10, 721, 561))
        self.mainGView.setObjectName("mainGView")
        self.btnFindOrient = QtGui.QPushButton(self.centralWidget)
        self.btnFindOrient.setGeometry(QtCore.QRect(770, 110, 131, 40))
        self.btnFindOrient.setObjectName("btnFindOrient")
        self.btnFindCal = QtGui.QPushButton(self.centralWidget)
        self.btnFindCal.setGeometry(QtCore.QRect(770, 70, 130, 40))
        self.btnFindCal.setObjectName("btnFindCal")
        self.lineEdit = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 580, 290, 30))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtGui.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(20, 610, 290, 20))
        self.label.setObjectName("label")
        self.btnCapture = QtGui.QPushButton(self.centralWidget)
        self.btnCapture.setGeometry(QtCore.QRect(840, 20, 113, 40))
        self.btnCapture.setObjectName("btnCapture")
        self.btnConnect = QtGui.QPushButton(self.centralWidget)
        self.btnConnect.setGeometry(QtCore.QRect(310, 578, 120, 40))
        self.btnConnect.setObjectName("btnConnect")
        self.lblDistCal = QtGui.QLabel(self.centralWidget)
        self.lblDistCal.setGeometry(QtCore.QRect(900, 80, 111, 16))
        self.lblDistCal.setAlignment(QtCore.Qt.AlignCenter)
        self.lblDistCal.setObjectName("lblDistCal")
        self.lblAngleOrient = QtGui.QLabel(self.centralWidget)
        self.lblAngleOrient.setGeometry(QtCore.QRect(900, 120, 111, 16))
        self.lblAngleOrient.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAngleOrient.setObjectName("lblAngleOrient")
        self.btnFind1 = QtGui.QPushButton(self.centralWidget)
        self.btnFind1.setGeometry(QtCore.QRect(780, 160, 51, 41))
        self.btnFind1.setObjectName("btnFind1")
        self.lblDist1 = QtGui.QLabel(self.centralWidget)
        self.lblDist1.setGeometry(QtCore.QRect(840, 170, 60, 16))
        self.lblDist1.setAlignment(QtCore.Qt.AlignCenter)
        self.lblDist1.setObjectName("lblDist1")
        self.lblAngle1 = QtGui.QLabel(self.centralWidget)
        self.lblAngle1.setGeometry(QtCore.QRect(910, 170, 60, 16))
        self.lblAngle1.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAngle1.setObjectName("lblAngle1")
        self.btnFind2 = QtGui.QPushButton(self.centralWidget)
        self.btnFind2.setGeometry(QtCore.QRect(780, 200, 51, 41))
        self.btnFind2.setObjectName("btnFind2")
        self.lblDist2 = QtGui.QLabel(self.centralWidget)
        self.lblDist2.setGeometry(QtCore.QRect(840, 210, 60, 16))
        self.lblDist2.setAlignment(QtCore.Qt.AlignCenter)
        self.lblDist2.setObjectName("lblDist2")
        self.lblAngle2 = QtGui.QLabel(self.centralWidget)
        self.lblAngle2.setGeometry(QtCore.QRect(910, 210, 60, 16))
        self.lblAngle2.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAngle2.setObjectName("lblAngle2")
        self.btnFind3 = QtGui.QPushButton(self.centralWidget)
        self.btnFind3.setGeometry(QtCore.QRect(780, 240, 51, 41))
        self.btnFind3.setObjectName("btnFind3")
        self.lblDist3 = QtGui.QLabel(self.centralWidget)
        self.lblDist3.setGeometry(QtCore.QRect(840, 250, 60, 16))
        self.lblDist3.setAlignment(QtCore.Qt.AlignCenter)
        self.lblDist3.setObjectName("lblDist3")
        self.lblAngle3 = QtGui.QLabel(self.centralWidget)
        self.lblAngle3.setGeometry(QtCore.QRect(910, 250, 60, 16))
        self.lblAngle3.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAngle3.setObjectName("lblAngle3")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar()
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1000, 22))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFindOrient.setText(QtGui.QApplication.translate("MainWindow", "Find Orientation", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFindCal.setText(QtGui.QApplication.translate("MainWindow", "Find Calibration", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Not connected", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCapture.setText(QtGui.QApplication.translate("MainWindow", "Capture", None, QtGui.QApplication.UnicodeUTF8))
        self.btnConnect.setText(QtGui.QApplication.translate("MainWindow", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDistCal.setText(QtGui.QApplication.translate("MainWindow", "---", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAngleOrient.setText(QtGui.QApplication.translate("MainWindow", "---", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFind1.setText(QtGui.QApplication.translate("MainWindow", "O", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDist1.setText(QtGui.QApplication.translate("MainWindow", "---", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAngle1.setText(QtGui.QApplication.translate("MainWindow", "---", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFind2.setText(QtGui.QApplication.translate("MainWindow", "O", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDist2.setText(QtGui.QApplication.translate("MainWindow", "---", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAngle2.setText(QtGui.QApplication.translate("MainWindow", "---", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFind3.setText(QtGui.QApplication.translate("MainWindow", "O", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDist3.setText(QtGui.QApplication.translate("MainWindow", "---", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAngle3.setText(QtGui.QApplication.translate("MainWindow", "---", None, QtGui.QApplication.UnicodeUTF8))

