# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Mon May 15 00:59:12 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 700)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.btnFindOrient = QtGui.QPushButton(self.centralWidget)
        self.btnFindOrient.setGeometry(QtCore.QRect(750, 120, 131, 40))
        self.btnFindOrient.setObjectName("btnFindOrient")
        self.btnFindCal = QtGui.QPushButton(self.centralWidget)
        self.btnFindCal.setGeometry(QtCore.QRect(750, 80, 130, 40))
        self.btnFindCal.setObjectName("btnFindCal")
        self.lineEdit = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 580, 441, 30))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtGui.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(20, 610, 441, 20))
        self.label.setObjectName("label")
        self.btnCapture = QtGui.QPushButton(self.centralWidget)
        self.btnCapture.setGeometry(QtCore.QRect(820, 30, 113, 40))
        self.btnCapture.setObjectName("btnCapture")
        self.btnConnect = QtGui.QPushButton(self.centralWidget)
        self.btnConnect.setGeometry(QtCore.QRect(470, 578, 120, 40))
        self.btnConnect.setObjectName("btnConnect")
        self.lblDistCal = QtGui.QLabel(self.centralWidget)
        self.lblDistCal.setGeometry(QtCore.QRect(880, 90, 111, 16))
        self.lblDistCal.setAlignment(QtCore.Qt.AlignCenter)
        self.lblDistCal.setObjectName("lblDistCal")
        self.lblAngleOrient = QtGui.QLabel(self.centralWidget)
        self.lblAngleOrient.setGeometry(QtCore.QRect(880, 130, 111, 16))
        self.lblAngleOrient.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAngleOrient.setObjectName("lblAngleOrient")
        self.mainTabWidget = QtGui.QTabWidget(self.centralWidget)
        self.mainTabWidget.setGeometry(QtCore.QRect(10, 10, 731, 561))
        self.mainTabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.mainTabWidget.setObjectName("mainTabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.mapGView = QtGui.QGraphicsView(self.tab)
        self.mapGView.setGeometry(QtCore.QRect(0, 0, 731, 541))
        self.mapGView.setObjectName("mapGView")
        self.mainTabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.mainGView = QtGui.QGraphicsView(self.tab_2)
        self.mainGView.setGeometry(QtCore.QRect(0, 0, 751, 551))
        self.mainGView.setObjectName("mainGView")
        self.mainTabWidget.addTab(self.tab_2, "")
        self.operationsTabWidget = QtGui.QTabWidget(self.centralWidget)
        self.operationsTabWidget.setEnabled(True)
        self.operationsTabWidget.setGeometry(QtCore.QRect(750, 170, 240, 460))
        self.operationsTabWidget.setObjectName("operationsTabWidget")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.btnLabelContainers = QtGui.QPushButton(self.tab_3)
        self.btnLabelContainers.setGeometry(QtCore.QRect(10, 20, 211, 40))
        self.btnLabelContainers.setObjectName("btnLabelContainers")
        self.operationsTabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_3 = QtGui.QLabel(self.tab_4)
        self.label_3.setGeometry(QtCore.QRect(90, 210, 70, 16))
        self.label_3.setObjectName("label_3")
        self.groupBox = QtGui.QGroupBox(self.tab_4)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 241, 191))
        self.groupBox.setObjectName("groupBox")
        self.btnFind3 = QtGui.QPushButton(self.groupBox)
        self.btnFind3.setGeometry(QtCore.QRect(30, 110, 51, 41))
        self.btnFind3.setObjectName("btnFind3")
        self.btnFind1 = QtGui.QPushButton(self.groupBox)
        self.btnFind1.setGeometry(QtCore.QRect(30, 30, 51, 41))
        self.btnFind1.setObjectName("btnFind1")
        self.btnFind2 = QtGui.QPushButton(self.groupBox)
        self.btnFind2.setGeometry(QtCore.QRect(30, 70, 51, 41))
        self.btnFind2.setObjectName("btnFind2")
        self.lblDist2 = QtGui.QLabel(self.groupBox)
        self.lblDist2.setGeometry(QtCore.QRect(90, 80, 60, 16))
        self.lblDist2.setAlignment(QtCore.Qt.AlignCenter)
        self.lblDist2.setObjectName("lblDist2")
        self.lblDist3 = QtGui.QLabel(self.groupBox)
        self.lblDist3.setGeometry(QtCore.QRect(90, 120, 60, 16))
        self.lblDist3.setAlignment(QtCore.Qt.AlignCenter)
        self.lblDist3.setObjectName("lblDist3")
        self.lblAngle3 = QtGui.QLabel(self.groupBox)
        self.lblAngle3.setGeometry(QtCore.QRect(160, 120, 60, 16))
        self.lblAngle3.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAngle3.setObjectName("lblAngle3")
        self.lblAngle2 = QtGui.QLabel(self.groupBox)
        self.lblAngle2.setGeometry(QtCore.QRect(160, 80, 60, 16))
        self.lblAngle2.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAngle2.setObjectName("lblAngle2")
        self.lblDist1 = QtGui.QLabel(self.groupBox)
        self.lblDist1.setGeometry(QtCore.QRect(90, 40, 60, 16))
        self.lblDist1.setAlignment(QtCore.Qt.AlignCenter)
        self.lblDist1.setObjectName("lblDist1")
        self.lblAngle1 = QtGui.QLabel(self.groupBox)
        self.lblAngle1.setGeometry(QtCore.QRect(160, 40, 60, 16))
        self.lblAngle1.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAngle1.setObjectName("lblAngle1")
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 160, 210, 31))
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.miniGView = QtGui.QGraphicsView(self.tab_4)
        self.miniGView.setGeometry(QtCore.QRect(10, 230, 211, 191))
        self.miniGView.setObjectName("miniGView")
        self.operationsTabWidget.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar()
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1000, 22))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)

        self.retranslateUi(MainWindow)
        self.mainTabWidget.setCurrentIndex(0)
        self.operationsTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Measurement Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFindOrient.setText(QtGui.QApplication.translate("MainWindow", "Find Orientation", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFindCal.setText(QtGui.QApplication.translate("MainWindow", "Find Calibration", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Not connected", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCapture.setText(QtGui.QApplication.translate("MainWindow", "Capture", None, QtGui.QApplication.UnicodeUTF8))
        self.btnConnect.setText(QtGui.QApplication.translate("MainWindow", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDistCal.setText(QtGui.QApplication.translate("MainWindow", "---", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAngleOrient.setText(QtGui.QApplication.translate("MainWindow", "---", None, QtGui.QApplication.UnicodeUTF8))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Map", None, QtGui.QApplication.UnicodeUTF8))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Measure", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLabelContainers.setText(QtGui.QApplication.translate("MainWindow", "Label Containers", None, QtGui.QApplication.UnicodeUTF8))
        self.operationsTabWidget.setTabText(self.operationsTabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Map", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Mini Map", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Measurement", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFind3.setText(QtGui.QApplication.translate("MainWindow", "O", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFind1.setText(QtGui.QApplication.translate("MainWindow", "O", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFind2.setText(QtGui.QApplication.translate("MainWindow", "O", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDist2.setText(QtGui.QApplication.translate("MainWindow", "---", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDist3.setText(QtGui.QApplication.translate("MainWindow", "---", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAngle3.setText(QtGui.QApplication.translate("MainWindow", "---", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAngle2.setText(QtGui.QApplication.translate("MainWindow", "---", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDist1.setText(QtGui.QApplication.translate("MainWindow", "---", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAngle1.setText(QtGui.QApplication.translate("MainWindow", "---", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "** Angle relative to leftmost box** ", None, QtGui.QApplication.UnicodeUTF8))
        self.operationsTabWidget.setTabText(self.operationsTabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "Measure", None, QtGui.QApplication.UnicodeUTF8))

