#!/bin/bash
#script to run the mjpeg player with known input and output locations

#Most basic run, will display camera to index html
#mjpg_streamer -i "/usr/local/lib/input_uvc.so" -o "/usr/local/lib/output_http.so -w /usr/local/www"

#More Advanced. Specifying Which port to send the video through
mjpg_streamer -i "/usr/local/lib/input_uvc.so -d /dev/video0 " -o "/usr/local/lib/output_http.so -w /var/www/html -p 8080"&


mjpg_streamer -i "/usr/local/lib/input_uvc.so -d /dev/video1 " -o "/usr/local/lib/output_http.so -w /var/www/html -p 8081"
